name: Continuous-Integration
on: [push]
jobs:
 build-project:
  runs-on: ubuntu-latest
  env:
    - DISPLAY=:99.0
  #  DISPLAY: 0.0
  steps:
   - run: sudo apt-get install python3-setuptools
   - run: pip3 install RPi.GPIO
   - run: sudo apt-get -y install python3-tk
  #  - run: pip3 install -U pytest
   - run: sudo python3 -m pip install pytest
   - name: Checkout Project
     uses: actions/checkout@v2
     with:
      python-version: '3.x'
   - run: make build
   - run: make check-ci
   - run: make check
