name: Continuous-Integration
on: [push]
jobs:
 build-project:
  runs-on: ubuntu-latest
  steps:
   - run: sudo apt-get install python3-setuptools
   - run: pip3 install RPi.GPIO
   - run: make prepare-dev
   - run: make build
