name: Continuous Integration
on: [push]
jobs:
 check-repo:
  runs-on: ubuntu-latest
   env:
    DISPLAY: 0.0
  steps:
   - run: sudo apt-get install python3-setuptools
   - run: pip3 install RPi.GPIO
   - run: sudo apt-get -y install python3-tk
   - run: pip3 install -U pytest
   - name: Checkout Project
     uses: actions/checkout@v2
   - name: Build Project
     run: make build
   - name: Run Tests
     run: make check
